version: '3.8'

services:
  crm-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Port exposé pour le backend
    environment:
      - PORT=8080
      - ADRESSE=0.0.0.0
      - HOST=http://localhost:3001
      - DB_HOST=adminphpvmco3.digilabo.net
      - DB_USER=dahmen
      - DB_PASSWORD=abdel2018*
      - DB_NAME=sofcem_base_crm
      - DB_PORT=3306
    networks:
      - crm-network

  crm-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # Port exposé pour le frontend
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge
